name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional --force
      - name: ESLint
        run: npm run lint
      - name: Unit test
        run:  npm run test:unit


